export default interface IScheduleResult {
    id: number,
    title: string| null,
    // start_time: string| null,
    // end_time: string| null,
    // location_id: number| null,
    // location_other_name: string| null,
    // leader_id: number| null,
    // leader_orther_name: string| null,
    // description: string| null,
    // type: number| null,
    // department_id: string| null,
    // create_by: string| null,
    // update_by: string| null,
    // close_by: string| null,
    // status: number| null,
    // is_public: boolean| null,
    // old_start_time: string| null,
    // old_end_time: string| null,
    // old_location_id: number| null,
    // old_location_other_name: string| null,
    // old_leader_id: number| null,
    // old_leader_orther_name: string| null,
    // old_title: string| null,
    // old_description: string| null,
    // old_type: number| null,
    // old_department_id: number | null,
}
